import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { MDXRemote } from 'next-mdx-remote';
import { serialize } from 'next-mdx-remote/serialize';

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'content', 'about.md');
  const source = fs.readFileSync(filePath, 'utf8');
  const { content } = matter(source);
  const mdxSource = await serialize(content);
  return { props: { mdxSource } };
}

export default function About({ mdxSource }) {
  return (
    <article>
      <MDXRemote {...mdxSource} />
    </article>
  );
}

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
