# This defines your build settings
[build]
  command = "npm run build"
  publish = "dist"

# Optional: redirect `/index.html` to `/` for cleanliness
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301