name: Deploy Node.js app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: aisolutionsconsulting.net
          allow_empty_commit: true
          destination_dir: ./
          source_dir: ./dist
          custom_domain: aisolutionsconsulting.net
          skip_cleanup: true
          publish_branch: gh-pages
          publish_dir: ./dist
          user_name: GitHub Actions
          user_email: actions@github.com
          commit_message: 'Deploy to GitHub Pages'

      - name: Rewrite index.html
        run: |
          echo "/*    /index.html   200" >> ./dist/_redirects
          cat ./dist/_redirects
