name: Auto Blog Fetch

on:
  schedule:
    - cron: '0 10 * * *' # Runs every day at 10:00 UTC (adjust as needed)
  workflow_dispatch:     # Allows manual triggering

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Fetch new blog posts
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: node scripts/fetch-news.js

      - name: Commit & push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/posts/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-update blog posts [skip ci]"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
