# .github/workflows/links.yml
name: Link Checker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣  Get the code
      - uses: actions/checkout@v4

      # 2️⃣  Install Node deps
      - name: Install Node packages
        run: npm ci

      # 3️⃣  Build the static site (Vite outputs to ./dist by default)
      - name: Build site
        run: npm run build

      # 4️⃣  Scan ./dist for links
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress ./dist
