# .github/workflows/links.yml
name: Link Checker

on:
  push:
    branches: [main]          # adjust as needed
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Pull the repo
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣  Set up Node (if you build with Node)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣  Install dependencies
      - name: Install packages
        run: npm ci

      # 4️⃣  Build the static site
      - name: Build site
        run: npm run build      # outputs to ./dist by default (Vite). Update if different.

      # 5️⃣  🐛 Debug: list what actually got built
      - name: List dist contents
        run: ls -laR ./dist

      # 6️⃣  Scan links
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # higher API rate limits for Lychee
        with:
          # Scan only HTML & MD files in dist; tweak pattern or folder if your output differs
          args: --verbose --no-progress "./dist/**/*.html" "./dist/**/*.md"
          failIfEmpty: false    # set to true once you confirm links are being found
